config/routes.rb
Example::Application.routes.draw do
  devise_for :users
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :desc
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])
    @product.save
    redirect_to products_path
  end

  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    @product.update_attributes(params[:product])
    redirect_to product_path(@product)
  end

  def show
    @product = Product.find(params[:id])
  end
 
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to new_product_path
  end
  
  def index
    @products = Product.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
<div>
  Product Name:
</div>
<div>
  <%= f.text_field :name %>
</div>

<div>
  Product Description
</div>

<div>
  <%= f.text_area :desc %>
</div>

<div>
  <%= f.submit %>
</div>

<% end %>

app/views/products/edit.html.erb
<%= render :partial=> 'products/form' %>

app/views/products/index.html.erb
<%= link_to "new", new_product_path %>
<table>
<tr>
<th>Product Name</th>
<th>Description</th>
<th></th>
<th></th>
</tr>
<% @products.each do |product| %>
<tr>
<td><%= product.name%></td>
<td><%= product.desc%></td>
<td><%= link_to "edit", edit_product_path(product) %> | <%= link_to "delete", product_path(product),:method => 'DELETE' %> |  <%= link_to "show", product_path(product) %></td>
<% end %>
</table>

app/views/products/new.html.erb
<%= render :partial=>'products/form' %>

app/views/products/show.html.erb
<p>ProductName:<%=@product.name%></p>
<p>ProductDescription:<%=@product.desc%></p>
<td><%= link_to "edit", edit_product_path(@product) %> | <%= link_to "delete", product_path(@product),:method => 'DELETE' %> </td>